### ISSUE TITLE
Creating a user after deleting throws exception

### ISSUE THREAD

**Issue by tonythomas01** [amfoss/club-website-2017#15]
[Errno 2] No such file or directory: 'images/profile_image/joyceg.jpg'
Exception Type: OSError
Exception Value:  
[Errno 2] No such file or directory: 'images/profile_image/joyceg.jpg'
Exception Location: /home/domains/foss/fosswebsite/images/models.py in get_available_name, line 60

**Comment by ash1794** [comment]
That's because the deletion of user doesn't delete the ProfileImage object which causes a conflict. Also deleting the ProfileImage object should delete the file. The necessary changes for the second part is already made when fixing Issue #8. I'm trying a fix. But the same error 503 might occur due to reasons mentioned in Issue #8.

**Comment by ash1794** [comment]
Since The bug isn't reproduced. I'm closing this.
